var S=JSON.parse(localStorage.getItem("linguabot-web")||"null")||{page:"learn",language:"en",xp:360,gems:500,hearts:5,streak:4,name:"Misafir Öğrenci",username:"misafir_kullanici",apiKey:"",messages:[{role:"byte",text:"Bip-bup! Merhaba! Ben Byte. Ödev, dil pratiği veya gelecek planın hakkında bana yaz."}],lessonId:null,exerciseIndex:0,lessonDone:{}};
var langs=[["en","🇬🇧","English"],["tr","🇹🇷","Türkçe"],["az","🇦🇿","Azərbaycanca"],["es","🇪🇸","Español"],["de","🇩🇪","Deutsch"],["fr","🇫🇷","Français"],["ja","🇯🇵","日本語"],["ko","🇰🇷","한국어"]];
function q(x){return document.querySelector(x)} function esc(x){return String(x??"").replace(/[&<>"]/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]})} function save(){localStorage.setItem("linguabot-web",JSON.stringify(S))}
function stats(){q("#streak").textContent=S.streak;q("#gems").textContent=S.gems;q("#hearts").textContent=S.hearts;q("#lang").textContent=(langs.find(function(x){return x[0]==S.language})||langs[0])[2]}
function getLessons(){return (window.LINGUABOT_CURRICULUM||[]).filter(function(l){return l.languageCode===S.language})}
function render(){stats();document.querySelectorAll("#nav button").forEach(function(b){b.classList.toggle("active",b.dataset.page==S.page)});({learn:learn,chat:chat,plan:plan,lab:lab,leaderboard:leaderboard,profile:profile,settings:settings}[S.page]||learn)(q("#page"));save()}
function learn(p){var ls=getLessons();if(!ls.length){p.innerHTML='<div class="card"><h2>Bu dil için dersler hazırlanıyor.</h2><p class="muted">Başka bir dil seçebilir veya Byte AI ile özel çalışma isteyebilirsin.</p></div>';return}var units={};ls.forEach(function(l){(units[l.unitNumber]||(units[l.unitNumber]=[])).push(l)});var h='<div class="hero"><div class="card"><span class="tag">ANDROID CURRICULUM → WEB</span><h1>Gerçek derslerin<br>web sürümü.</h1><p class="muted">'+ls.length+' ders ve '+ls.reduce(function(n,l){return n+l.exercises.length},0)+' egzersiz hazır. Android uygulamasındaki müfredat buradan oynatılıyor.</p><button class="btn" data-act="startFirst">Derse Başla →</button></div><div class="card robot"><img src="https://raw.githubusercontent.com/mm2vault/LinguaBot/main/app/src/main/res/drawable/img_robot_companion.jpg"><div><span class="tag">BYTE</span><h2>Hazırım.</h2><p class="muted">Kelime, cümle, eşleştirme, boşluk doldurma ve konuşma pratiği.</p><button class="btn" data-act="poke">Robotu dürt</button></div></div></div>';
Object.keys(units).sort(function(a,b){return a-b}).forEach(function(u){h+='<h2 class="section">Ünite '+u+'</h2><div class="grid">';units[u].forEach(function(l){var done=S.lessonDone[l.id],pct=done?100:0;h+='<button class="card lessonCard" data-lesson="'+esc(l.id)+'"><span class="lessonIcon">'+(l.isMilestone?"👑":l.iconType==="coffee"?"☕":l.iconType==="airplane"?"✈️":l.iconType==="speech"?"💬":"⭐")+'</span><b>Ünite '+l.unitNumber+'</b><h3>'+esc(l.title)+'</h3><p class="muted">'+esc(l.subtitle||l.unitDescription)+'</p><div class="progress"><i style="width:'+pct+'%"></i></div><small>+'+l.xpReward+' XP · '+l.exercises.length+' egzersiz</small></button>'});h+='</div>'});p.innerHTML=h}
function currentLesson(){return (window.LINGUABOT_CURRICULUM||[]).find(function(l){return l.id===S.lessonId})}
function lessonScreen(p){var l=currentLesson();if(!l){S.page="learn";render();return}var ex=l.exercises[S.exerciseIndex];if(!ex){S.lessonDone[l.id]=true;S.xp+=l.xpReward;S.gems+=l.gemReward||10;S.hearts=Math.min(5,S.hearts+1);S.lessonId=null;S.exerciseIndex=0;alert("🎉 Ders tamamlandı! +"+l.xpReward+" XP");render();return}var h='<div class="card exercise"><button class="ghost" data-act="backLearn">← Öğrenmeye dön</button><span class="tag">'+esc(l.title)+' · '+(S.exerciseIndex+1)+'/'+l.exercises.length+'</span><h1>'+esc(ex.prompt)+'</h1>';
if(ex.type==="MULTIPLE_CHOICE")h+='<div class="options">'+ex.options.map(function(o){return '<button class="option" data-answer="'+esc(o)+'">'+esc(o)+'</button>'}).join("")+'</div>';
else if(ex.type==="FILL_BLANK")h+='<input id="answer" placeholder="Cevabını yaz..."><button class="btn" data-act="textAnswer">Kontrol et</button>';
else if(ex.type==="SENTENCE_ORDER"){var words=(ex.options||[]).slice().sort(function(){return Math.random()-.5});h+='<p class="muted">Kelimelere sırayla dokun:</p><div id="wordBank" class="wordBank">'+words.map(function(w){return '<button class="word" data-word="'+esc(w)+'">'+esc(w)+'</button>'}).join("")+'</div><div id="sentence" class="answerLine"></div><button class="btn" data-act="sentenceAnswer">Kontrol et</button>'}
else if(ex.type==="MATCH_PAIRS"){h+='<div class="matchGrid">';Object.keys(ex.pairMap||{}).forEach(function(k){h+='<button class="option match" data-match="'+esc(k)+'">'+esc(k)+'</button>'});h+='</div><p class="muted">Bir karta dokun ve doğru anlamı seç.</p><div id="matchAnswers" class="options"></div>'}
else if(ex.type==="SPEAK_PRONOUNCE"){h+='<div class="speakBox"><div class="target">'+esc(ex.correctAnswer||ex.ttsTargetText||"")+'</div><button class="btn" data-act="speak">🎙️ Konuş</button><button class="ghost" data-act="listen">🔊 Dinle</button><p id="speechResult" class="muted"></p></div>'}
else h+='<input id="answer" placeholder="Cevabını yaz..."><button class="btn" data-act="textAnswer">Kontrol et</button>';
h+='<p id="feedback" class="feedback"></p></div>';p.innerHTML=h}
function check(ok,ex){var f=q("#feedback");if(ok){f.textContent="✅ Doğru! "+(ex.explanation||"Byte gurur duyuyor.");f.className="feedback good";S.xp+=5;setTimeout(function(){S.exerciseIndex++;renderExercise()},650)}else{f.textContent="❌ Henüz değil. "+(ex.explanation||"Tekrar düşün ve yeniden dene.");f.className="feedback bad";S.hearts=Math.max(0,S.hearts-1);stats()};save()}
function renderExercise(){lessonScreen(q("#page"));S.page="learn";document.querySelectorAll("#nav button").forEach(function(b){b.classList.remove("active")})}
function chat(p){var h='<div class="card chat"><h2>Byte AI</h2><p class="muted">Ödevini açıkla, çeviri iste veya derslerine ve hedeflerine göre gelecek planı oluştur.</p><div class="messages">';S.messages.forEach(function(m){h+='<div class="bubble '+m.role+'">'+esc(m.text)+'</div>'});h+='</div><div class="chatbox"><textarea id="msg" rows="2" placeholder="Byte\'a yaz..."></textarea><button class="btn" data-act="send">Gönder</button></div></div>';p.innerHTML=h}
function plan(p){var ls=getLessons().filter(function(l){return !S.lessonDone[l.id]}).slice(0,3);p.innerHTML='<div class="card"><span class="tag">AI ADAPTIVE PLAN</span><h1>Senin çalışma planın.</h1><p class="muted">Gerçek Android müfredatından eksik dersleri seçerek web tarafında günlük rota oluşturuyoruz.</p><div class="stats"><div class="stat">XP<strong>'+S.xp+'</strong></div><div class="stat">Kalp<strong>'+S.hearts+'</strong></div><div class="stat">Günlük<strong>30 dk</strong></div><div class="stat">Seri<strong>'+S.streak+' gün</strong></div></div><h2 class="section">Bugünkü rota</h2><div class="grid">'+(ls.length?ls.map(function(l,i){return '<button class="card lessonCard" data-lesson="'+esc(l.id)+'"><h3>'+(i+1)+' · '+esc(l.title)+'</h3><p class="muted">'+esc(l.unitDescription)+'</p><small>'+l.exercises.length+' egzersiz · +'+l.xpReward+' XP</small></button>'}).join(""):'<div class="card"><h3>🎉 Rota tamamlandı</h3><p class="muted">Yeni derslerin kilidi açıldı.</p></div>')+'</div></div>'}
function lab(p){p.innerHTML='<div class="hero"><div class="card"><span class="tag">ROBOT LAB</span><h1>Byte\'ı geliştir.</h1><p class="muted">Kalpler ve gemiler yerel olarak saklanır.</p><button class="btn" data-act="refill">100 💎 → 5 ❤️</button></div><div class="card robot"><img src="https://raw.githubusercontent.com/mm2vault/LinguaBot/main/app/src/main/res/drawable/img_robot_companion.jpg"><div><h2>Byte</h2><p class="muted">Bip-bop! Sistemler nominal.</p></div></div></div>'}
function leaderboard(p){var u=["Aylin K.","Sen (Öğrenci)","Murad Ə.","Carlos M.","Elena V.","Kenji T."],xp=[480,S.xp,340,310,290,260];p.innerHTML='<div class="card"><h2>Liderlik</h2>'+u.map(function(n,i){return '<div class="row"><b>#'+(i+1)+' '+n+'</b><strong>'+xp[i]+' XP</strong></div>'}).join("")+'</div>'}
function profile(p){p.innerHTML='<div class="hero"><div class="card"><span class="tag">PROFİL</span><h1>'+esc(S.name)+'</h1><p class="muted">@'+esc(S.username)+'</p></div><div class="card"><h2>Profil düzenle</h2><p><input id="name" value="'+esc(S.name)+'"></p><p><input id="username" value="'+esc(S.username)+'"></p><button class="btn" data-act="saveProfile">Kaydet</button></div></div>'}
function settings(p){p.innerHTML='<div class="card"><span class="tag">AYARLAR</span><h2>Gemini bağlantısı</h2><p class="muted">API anahtarı yalnızca bu tarayıcıda tutulur. Herkese açık projede güvenli proxy kullanmak daha doğru olur.</p><p><input id="key" type="password" value="'+esc(S.apiKey)+'" placeholder="Gemini API key"></p><button class="btn" data-act="saveKey">Kaydet</button><button class="btn" data-act="reset">Yerel veriyi sıfırla</button></div>'}
async function send(){var x=q("#msg"),t=x.value.trim();if(!t)return;S.messages.push({role:"user",text:t});render();if(!S.apiKey){S.messages.push({role:"byte",text:"Bip! Gemini anahtarın Ayarlar bölümünde yok. Anahtar eklersen gerçek AI cevapları kullanırım."});render();return}try{var r=await fetch("https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key="+encodeURIComponent(S.apiKey),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({contents:[{parts:[{text:"Sen LinguaBot Byte robotusun. Türkçe cevap ver. Kullanıcının dil derslerini, okul ödevlerini ve gelecek planlarını birlikte yönet. Ders müfredatı: "+getLessons().slice(0,12).map(function(l){return l.title}).join(", ")+" Kullanıcı: "+t}]}]})});var j=await r.json(),a=j.candidates&&j.candidates[0]&&j.candidates[0].content.parts[0].text;if(!a)throw Error(j.error&&j.error.message||"AI cevap vermedi");S.messages.push({role:"byte",text:a})}catch(e){S.messages.push({role:"byte",text:"Byte bağlantısı hata verdi: "+e.message})}render()}
document.addEventListener("click",function(e){var n=e.target.closest("[data-page]");if(n){S.page=n.dataset.page;q(".sidebar").classList.remove("open");render();return}var card=e.target.closest("[data-lesson]");if(card){S.lessonId=card.dataset.lesson;S.exerciseIndex=0;lessonScreen(q("#page"));return}var word=e.target.closest("[data-word]");if(word){q("#sentence").textContent=(q("#sentence").textContent+" "+word.dataset.word).trim();word.disabled=true;return}var a=e.target.closest("[data-act]");if(!a)return;var z=a.dataset.act;if(z=="send")send();if(z=="startFirst"){var l=getLessons()[0];if(l){S.lessonId=l.id;S.exerciseIndex=0;lessonScreen(q("#page"))}}if(z=="backLearn"){S.lessonId=null;render()}if(z=="poke")alert("Byte: Bip-bup! Gıdıklandım. 😤");if(z=="refill"&&S.gems>=100){S.gems-=100;S.hearts=5;render()}if(z=="saveProfile"){S.name=q("#name").value;S.username=q("#username").value;render()}if(z=="saveKey"){S.apiKey=q("#key").value.trim();save();alert("Kaydedildi.");render()}if(z=="reset"&&confirm("Yerel ilerleme silinsin mi?")){localStorage.removeItem("linguabot-web");location.reload()}
var l=currentLesson(),ex=l&&l.exercises[S.exerciseIndex];if(!ex)return;if(z=="textAnswer")check(q("#answer").value.trim().toLowerCase()===String(ex.correctAnswer).trim().toLowerCase(),ex);if(z=="sentenceAnswer")check(q("#sentence").textContent.trim()===String(ex.correctAnswer).trim(),ex);if(z=="listen"){if("speechSynthesis"in window){var u=new SpeechSynthesisUtterance(ex.ttsTargetText||ex.correctAnswer);u.lang=S.language;speechSynthesis.speak(u)}}if(z=="speak"&&"webkitSpeechRecognition"in window){var R=new webkitSpeechRecognition();R.lang=S.language;R.onresult=function(ev){var said=ev.results[0][0].transcript;q("#speechResult").textContent="Dedin: "+said;check(said.toLowerCase().replace(/[^a-z\u00C0-\u024F\u3040-\u30ff\uac00-\ud7af\u4e00-\u9fff ]/gi,"").trim()===String(ex.correctAnswer||ex.ttsTargetText).toLowerCase().trim(),ex)};R.start()}});
q("#menu").onclick=function(){q(".sidebar").classList.toggle("open")};q("#language").onclick=function(){q("#langs").showModal()};q("#close").onclick=function(){q("#langs").close()};q("#langGrid").innerHTML=langs.map(function(l){return '<button class="langOpt" data-lang="'+l[0]+'">'+l[1]+" "+l[2]+"</button>"}).join("");document.addEventListener("click",function(e){var b=e.target.closest(".langOpt");if(b){S.language=b.dataset.lang;S.lessonId=null;q("#langs").close();render()}});render();


/* ===== Gamification enhancement layer ===== */
(function(){
  var oldRender=render, oldLearn=learn, oldLeaderboard=leaderboard, oldProfile=profile;
  var todayKey=new Date().toISOString().slice(0,10);
  S.daily=S.daily||{date:todayKey,completed:[]};
  if(S.daily.date!==todayKey){S.daily={date:todayKey,completed:[]};S.streak=Math.max(1,(S.streak||0)+1);}
  S.badges=S.badges||[];
  function completedLessons(){return Object.keys(S.lessonDone||{}).filter(function(k){return S.lessonDone[k]}).length}
  function tasks(){return [
    {id:"lesson",icon:"📚",title:"Bir ders tamamla",goal:1,value:completedLessons()-(S.daily.baseLessons||0),reward:30},
    {id:"xp",icon:"⚡",title:"50 XP kazan",goal:50,value:S.daily.xp||0,reward:20},
    {id:"chat",icon:"🤖",title:"Byte ile konuş",goal:1,value:S.daily.chat||0,reward:15}
  ]}
  S.daily.baseLessons=S.daily.baseLessons||completedLessons();
  function awardBadge(id){if(S.badges.indexOf(id)<0){S.badges.push(id);S.gems+=25;return true}return false}
  function syncBadges(){if(S.streak>=7)awardBadge("week");if(completedLessons()>=5)awardBadge("learner");if(S.xp>=1000)awardBadge("xp1000")}
  function addXP(n){S.xp+=n;S.daily.xp=(S.daily.xp||0)+n;syncBadges();save()}
  function taskCard(t){var v=Math.max(0,Math.min(t.goal,t.value||0)),pct=Math.round(v/t.goal*100);return '<div class="quest"><div class="questIcon">'+t.icon+'</div><div style="flex:1"><b>'+t.title+'</b><div class="muted"><small>'+v+' / '+t.goal+' · +'+t.reward+' XP</small></div><div class="questBar"><i style="width:'+pct+'%"></i></div></div><b>'+pct+'%</b></div>'}
  function tasksPage(p){var ts=tasks();p.innerHTML='<div class="pageInner"><div class="streakCard card"><div><span class="tag">BUGÜN</span><h1>Günlük görevlerin</h1><p class="muted">Küçük adımlar, büyük seri. Görevleri tamamla ve ödülleri topla.</p></div><div class="flame">🔥</div></div><div class="section"><h2>🎯 Bugünün görevleri</h2></div><div class="gameGrid"><div class="card">'+ts.map(taskCard).join('')+'<button class="btn" data-act="claimTasks">Tamamlanan ödülleri al</button></div><div class="card"><h2>⏰ Hatırlatıcı</h2><p class="muted">Günlük çalışma hedefini kaçırmamak için tarayıcı hatırlatıcısını aç.</p><button class="btn" data-act="reminder">🔔 Hatırlatıcıyı aç</button><p id="reminderStatus" class="muted"></p></div></div></div>'}
  function statsPage(p){var done=completedLessons(),ls=getLessons().length,accuracy=Math.min(100,Math.round((S.xp/Math.max(1,(done*30+S.xp)))*100+55)),days=Math.min(7,S.streak||0),vals=[30,55,42,72,60,86,Math.max(15,days*13)];p.innerHTML='<div class="card"><span class="tag">İLERLEME MERKEZİ</span><h1>Gelişimini gör. 📊</h1><p class="muted">Öğrenme alışkanlığını tek ekranda takip et.</p><div class="stats"><div class="stat">Toplam XP<strong>'+S.xp+'</strong></div><div class="stat">Ders<strong>'+done+' / '+ls+'</strong></div><div class="stat">Doğruluk<strong>'+accuracy+'%</strong></div><div class="stat">Seri<strong>'+S.streak+' gün</strong></div></div></div><div class="section"><h2>Haftalık aktivite</h2></div><div class="card"><div class="chart">'+vals.map(function(v,i){return '<div class="bar" style="height:'+v+'%"><span>'+["Pzt","Sal","Çar","Per","Cum","Cmt","Paz"][i]+'</span></div>'}).join('')+'</div></div><div class="section"><h2>📈 Öğrenme özeti</h2></div><div class="grid"><div class="card"><h3>🔥 Seri</h3><p class="muted">Bugün dahil '+S.streak+' günlük çalışma.</p></div><div class="card"><h3>💎 Ödüller</h3><p class="muted">'+S.gems+' gem biriktirdin.</p></div><div class="card"><h3>📚 Müfredat</h3><p class="muted">'+ls+' gerçek ders, egzersizlerinle birlikte hazır.</p></div></div>'}
  function badgesPage(p){var all=[["first","🌱","İlk Adım","İlk dersini tamamla",completedLessons()>=1],["learner","📚","Düzenli Öğrenci","5 ders tamamla",completedLessons()>=5],["week","🔥","7 Günlük Seri","7 gün üst üste çalış",S.streak>=7],["xp1000","⚡","XP Ustası","1000 XP kazan",S.xp>=1000],["social","📣","Paylaşımcı","İlerlemeni paylaş",S.badges.indexOf("social")>=0],["byte","🤖","Byte Dostu","Byte ile konuş",S.daily.chat>=1]];p.innerHTML='<div class="card"><span class="tag">BAŞARILAR</span><h1>Rozet koleksiyonun</h1><p class="muted">Her rozet bir öğrenme alışkanlığını temsil eder.</p><div class="badges">'+all.map(function(b){return '<div class="badge '+(b[4]?'':'locked')+'"><div class="badgeIcon">'+b[1]+'</div><h3>'+b[2]+'</h3><small class="muted">'+b[3]+'</small></div>'}).join('')+'</div></div>'}
  function share(){var text="LinguaBot'ta bugün "+S.xp+" XP ve "+S.streak+" günlük seri yaptım! 🔥";awardBadge("social");if(navigator.share)navigator.share({title:"LinguaBot",text:text,url:location.href}).catch(function(){});else if(navigator.clipboard)navigator.clipboard.writeText(text+" "+location.href).then(function(){alert("Paylaşım metni kopyalandı!")});else alert(text)}
  function enhancedLearn(p){oldLearn(p);var wrap=document.createElement("div");wrap.innerHTML='<div class="section"><h2>🎯 Bugünkü mini görev</h2></div><div class="card quest"><div class="questIcon">⚡</div><div style="flex:1"><b>50 XP kazan</b><div class="questBar"><i style="width:'+Math.min(100,(S.daily.xp||0)*2)+'%"></i></div></div><strong>'+(S.daily.xp||0)+'/50</strong></div><div class="section"><h2>📣 İlerlemeni paylaş</h2></div><div class="shareRow"><button class="shareBtn" data-act="share">📤 Paylaş</button><button class="shareBtn" data-act="shareCopy">🔗 Linki kopyala</button></div>';p.appendChild(wrap)}
  learn=enhancedLearn;
  render=function(){stats();syncBadges();document.querySelectorAll("#nav button").forEach(function(b){b.classList.toggle("active",b.dataset.page==S.page)});var fn={learn:learn,chat:chat,plan:plan,lab:lab,leaderboard:leaderboard,profile:profile,settings:settings,tasks:tasksPage,stats:statsPage,badges:badgesPage}[S.page]||learn;fn(q("#page"));save()};
  document.addEventListener("click",function(e){
    var a=e.target.closest("[data-act]");if(!a)return;var z=a.dataset.act;
    if(z==="claimTasks"){var ts=tasks(),got=0;ts.forEach(function(t){var done=(t.value||0)>=t.goal;if(done&&S.daily.completed.indexOf(t.id)<0){S.daily.completed.push(t.id);S.xp+=t.reward;got+=t.reward}});save();alert(got?"🎁 +"+got+" XP ödülünü aldın!":"Önce görevleri tamamla.");render()}
    if(z==="reminder"){if("Notification"in window){Notification.requestPermission().then(function(x){q("#reminderStatus").textContent=x==="granted"?"🔔 Hatırlatıcı izni verildi.":"İzin verilmedi."})}else q("#reminderStatus").textContent="Tarayıcın bildirimleri desteklemiyor."}
    if(z==="share")share();
    if(z==="shareCopy"){awardBadge("social");var u=location.href;navigator.clipboard?navigator.clipboard.writeText(u).then(function(){alert("Link kopyalandı!") }):alert(u)}
  });
  var oldSend=send;send=async function(){S.daily.chat=(S.daily.chat||0)+1;syncBadges();await oldSend();render()};
  var oldLessonScreen=lessonScreen;lessonScreen=function(p){oldLessonScreen(p)};
  var oldCheck=check;check=function(ok,ex){if(ok)addXP(5);oldCheck(ok,ex);};
  render();
})();