var S=JSON.parse(localStorage.getItem("linguabot-web")||"null")||{page:"learn",language:"en",xp:360,gems:500,hearts:5,streak:4,name:"Misafir Öğrenci",username:"misafir_kullanici",apiKey:"",messages:[{role:"byte",text:"Bip-bup! Merhaba! Ben Byte. Ödev, dil pratiği veya gelecek planın hakkında bana yaz."}],lessonId:null,exerciseIndex:0,lessonDone:{}};
var langs=[["en","🇬🇧","English"],["tr","🇹🇷","Türkçe"],["az","🇦🇿","Azərbaycanca"],["es","🇪🇸","Español"],["de","🇩🇪","Deutsch"],["fr","🇫🇷","Français"],["ja","🇯🇵","日本語"],["ko","🇰🇷","한국어"]];
function q(x){return document.querySelector(x)} function esc(x){return String(x??"").replace(/[&<>"]/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]})} function save(){localStorage.setItem("linguabot-web",JSON.stringify(S))}
function stats(){q("#streak").textContent=S.streak;q("#gems").textContent=S.gems;q("#hearts").textContent=S.hearts;q("#lang").textContent=(langs.find(function(x){return x[0]==S.language})||langs[0])[2]}
function getLessons(){return (window.LINGUABOT_CURRICULUM||[]).filter(function(l){return l.languageCode===S.language})}
function render(){stats();document.querySelectorAll("#nav button").forEach(function(b){b.classList.toggle("active",b.dataset.page==S.page)});({learn:learn,chat:chat,plan:plan,lab:lab,leaderboard:leaderboard,profile:profile,settings:settings}[S.page]||learn)(q("#page"));save()}
function learn(p){var ls=getLessons();if(!ls.length){p.innerHTML='<div class="card"><h2>Bu dil için dersler hazırlanıyor.</h2><p class="muted">Başka bir dil seçebilir veya Byte AI ile özel çalışma isteyebilirsin.</p></div>';return}var units={};ls.forEach(function(l){(units[l.unitNumber]||(units[l.unitNumber]=[])).push(l)});var h='<div class="hero"><div class="card"><span class="tag">ANDROID CURRICULUM → WEB</span><h1>Gerçek derslerin<br>web sürümü.</h1><p class="muted">'+ls.length+' ders ve '+ls.reduce(function(n,l){return n+l.exercises.length},0)+' egzersiz hazır. Android uygulamasındaki müfredat buradan oynatılıyor.</p><button class="btn" data-act="startFirst">Derse Başla →</button></div><div class="card robot"><img src="https://raw.githubusercontent.com/mm2vault/LinguaBot/main/app/src/main/res/drawable/img_robot_companion.jpg"><div><span class="tag">BYTE</span><h2>Hazırım.</h2><p class="muted">Kelime, cümle, eşleştirme, boşluk doldurma ve konuşma pratiği.</p><button class="btn" data-act="poke">Robotu dürt</button></div></div></div>';
Object.keys(units).sort(function(a,b){return a-b}).forEach(function(u){h+='<h2 class="section">Ünite '+u+'</h2><div class="grid">';units[u].forEach(function(l){var done=S.lessonDone[l.id],pct=done?100:0;h+='<button class="card lessonCard" data-lesson="'+esc(l.id)+'"><span class="lessonIcon">'+(l.isMilestone?"👑":l.iconType==="coffee"?"☕":l.iconType==="airplane"?"✈️":l.iconType==="speech"?"💬":"⭐")+'</span><b>Ünite '+l.unitNumber+'</b><h3>'+esc(l.title)+'</h3><p class="muted">'+esc(l.subtitle||l.unitDescription)+'</p><div class="progress"><i style="width:'+pct+'%"></i></div><small>+'+l.xpReward+' XP · '+l.exercises.length+' egzersiz</small></button>'});h+='</div>'});p.innerHTML=h}
function currentLesson(){return (window.LINGUABOT_CURRICULUM||[]).find(function(l){return l.id===S.lessonId})}
function lessonScreen(p){var l=currentLesson();if(!l){S.page="learn";render();return}var ex=l.exercises[S.exerciseIndex];if(!ex){S.lessonDone[l.id]=true;S.xp+=l.xpReward;S.gems+=l.gemReward||10;S.hearts=Math.min(5,S.hearts+1);S.lessonId=null;S.exerciseIndex=0;alert("🎉 Ders tamamlandı! +"+l.xpReward+" XP");render();return}var h='<div class="card exercise"><button class="ghost" data-act="backLearn">← Öğrenmeye dön</button><span class="tag">'+esc(l.title)+' · '+(S.exerciseIndex+1)+'/'+l.exercises.length+'</span><h1>'+esc(ex.prompt)+'</h1>';
if(ex.type==="MULTIPLE_CHOICE")h+='<div class="options">'+ex.options.map(function(o){return '<button class="option" data-answer="'+esc(o)+'">'+esc(o)+'</button>'}).join("")+'</div>';
else if(ex.type==="FILL_BLANK")h+='<input id="answer" placeholder="Cevabını yaz..."><button class="btn" data-act="textAnswer">Kontrol et</button>';
else if(ex.type==="SENTENCE_ORDER"){var words=(ex.options||[]).slice().sort(function(){return Math.random()-.5});h+='<p class="muted">Kelimelere sırayla dokun:</p><div id="wordBank" class="wordBank">'+words.map(function(w){return '<button class="word" data-word="'+esc(w)+'">'+esc(w)+'</button>'}).join("")+'</div><div id="sentence" class="answerLine"></div><button class="btn" data-act="sentenceAnswer">Kontrol et</button>'}
else if(ex.type==="MATCH_PAIRS"){h+='<div class="matchGrid">';Object.keys(ex.pairMap||{}).forEach(function(k){h+='<button class="option match" data-match="'+esc(k)+'">'+esc(k)+'</button>'});h+='</div><p class="muted">Bir karta dokun ve doğru anlamı seç.</p><div id="matchAnswers" class="options"></div>'}
else if(ex.type==="SPEAK_PRONOUNCE"){h+='<div class="speakBox"><div class="target">'+esc(ex.correctAnswer||ex.ttsTargetText||"")+'</div><button class="btn" data-act="speak">🎙️ Konuş</button><button class="ghost" data-act="listen">🔊 Dinle</button><p id="speechResult" class="muted"></p></div>'}
else h+='<input id="answer" placeholder="Cevabını yaz..."><button class="btn" data-act="textAnswer">Kontrol et</button>';
h+='<p id="feedback" class="feedback"></p></div>';p.innerHTML=h}
function check(ok,ex){var f=q("#feedback");if(ok){f.textContent="✅ Doğru! "+(ex.explanation||"Byte gurur duyuyor.");f.className="feedback good";S.xp+=5;setTimeout(function(){S.exerciseIndex++;renderExercise()},650)}else{f.textContent="❌ Henüz değil. "+(ex.explanation||"Tekrar düşün ve yeniden dene.");f.className="feedback bad";S.hearts=Math.max(0,S.hearts-1);stats()};save()}
function renderExercise(){lessonScreen(q("#page"));S.page="learn";document.querySelectorAll("#nav button").forEach(function(b){b.classList.remove("active")})}
function chat(p){var h='<div class="card chat"><h2>Byte AI</h2><p class="muted">Ödevini açıkla, çeviri iste veya derslerine ve hedeflerine göre gelecek planı oluştur.</p><div class="messages">';S.messages.forEach(function(m){h+='<div class="bubble '+m.role+'">'+esc(m.text)+'</div>'});h+='</div><div class="chatbox"><textarea id="msg" rows="2" placeholder="Byte\'a yaz..."></textarea><button class="btn" data-act="send">Gönder</button></div></div>';p.innerHTML=h}
function plan(p){var ls=getLessons().filter(function(l){return !S.lessonDone[l.id]}).slice(0,3);p.innerHTML='<div class="card"><span class="tag">AI ADAPTIVE PLAN</span><h1>Senin çalışma planın.</h1><p class="muted">Gerçek Android müfredatından eksik dersleri seçerek web tarafında günlük rota oluşturuyoruz.</p><div class="stats"><div class="stat">XP<strong>'+S.xp+'</strong></div><div class="stat">Kalp<strong>'+S.hearts+'</strong></div><div class="stat">Günlük<strong>30 dk</strong></div><div class="stat">Seri<strong>'+S.streak+' gün</strong></div></div><h2 class="section">Bugünkü rota</h2><div class="grid">'+(ls.length?ls.map(function(l,i){return '<button class="card lessonCard" data-lesson="'+esc(l.id)+'"><h3>'+(i+1)+' · '+esc(l.title)+'</h3><p class="muted">'+esc(l.unitDescription)+'</p><small>'+l.exercises.length+' egzersiz · +'+l.xpReward+' XP</small></button>'}).join(""):'<div class="card"><h3>🎉 Rota tamamlandı</h3><p class="muted">Yeni derslerin kilidi açıldı.</p></div>')+'</div></div>'}
function lab(p){p.innerHTML='<div class="hero"><div class="card"><span class="tag">ROBOT LAB</span><h1>Byte\'ı geliştir.</h1><p class="muted">Kalpler ve gemiler yerel olarak saklanır.</p><button class="btn" data-act="refill">100 💎 → 5 ❤️</button></div><div class="card robot"><img src="https://raw.githubusercontent.com/mm2vault/LinguaBot/main/app/src/main/res/drawable/img_robot_companion.jpg"><div><h2>Byte</h2><p class="muted">Bip-bop! Sistemler nominal.</p></div></div></div>'}
function leaderboard(p){var u=["Aylin K.","Sen (Öğrenci)","Murad Ə.","Carlos M.","Elena V.","Kenji T."],xp=[480,S.xp,340,310,290,260];p.innerHTML='<div class="card"><h2>Liderlik</h2>'+u.map(function(n,i){return '<div class="row"><b>#'+(i+1)+' '+n+'</b><strong>'+xp[i]+' XP</strong></div>'}).join("")+'</div>'}
function profile(p){p.innerHTML='<div class="hero"><div class="card"><span class="tag">PROFİL</span><h1>'+esc(S.name)+'</h1><p class="muted">@'+esc(S.username)+'</p></div><div class="card"><h2>Profil düzenle</h2><p><input id="name" value="'+esc(S.name)+'"></p><p><input id="username" value="'+esc(S.username)+'"></p><button class="btn" data-act="saveProfile">Kaydet</button></div></div>'}
function settings(p){p.innerHTML='<div class="card"><span class="tag">AYARLAR</span><h2>Gemini bağlantısı</h2><p class="muted">API anahtarı yalnızca bu tarayıcıda tutulur. Herkese açık projede güvenli proxy kullanmak daha doğru olur.</p><p><input id="key" type="password" value="'+esc(S.apiKey)+'" placeholder="Gemini API key"></p><button class="btn" data-act="saveKey">Kaydet</button><button class="btn" data-act="reset">Yerel veriyi sıfırla</button></div>'}
async function send(){var x=q("#msg"),t=x.value.trim();if(!t)return;S.messages.push({role:"user",text:t});render();if(!S.apiKey){S.messages.push({role:"byte",text:"Bip! Gemini anahtarın Ayarlar bölümünde yok. Anahtar eklersen gerçek AI cevapları kullanırım."});render();return}try{var r=await fetch("https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key="+encodeURIComponent(S.apiKey),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({contents:[{parts:[{text:"Sen LinguaBot Byte robotusun. Türkçe cevap ver. Kullanıcının dil derslerini, okul ödevlerini ve gelecek planlarını birlikte yönet. Ders müfredatı: "+getLessons().slice(0,12).map(function(l){return l.title}).join(", ")+" Kullanıcı: "+t}]}]})});var j=await r.json(),a=j.candidates&&j.candidates[0]&&j.candidates[0].content.parts[0].text;if(!a)throw Error(j.error&&j.error.message||"AI cevap vermedi");S.messages.push({role:"byte",text:a})}catch(e){S.messages.push({role:"byte",text:"Byte bağlantısı hata verdi: "+e.message})}render()}
document.addEventListener("click",function(e){var n=e.target.closest("[data-page]");if(n){S.page=n.dataset.page;q(".sidebar").classList.remove("open");render();return}var card=e.target.closest("[data-lesson]");if(card){S.lessonId=card.dataset.lesson;S.exerciseIndex=0;lessonScreen(q("#page"));return}var word=e.target.closest("[data-word]");if(word){q("#sentence").textContent=(q("#sentence").textContent+" "+word.dataset.word).trim();word.disabled=true;return}var a=e.target.closest("[data-act]");if(!a)return;var z=a.dataset.act;if(z=="send")send();if(z=="startFirst"){var l=getLessons()[0];if(l){S.lessonId=l.id;S.exerciseIndex=0;lessonScreen(q("#page"))}}if(z=="backLearn"){S.lessonId=null;render()}if(z=="poke")alert("Byte: Bip-bup! Gıdıklandım. 😤");if(z=="refill"&&S.gems>=100){S.gems-=100;S.hearts=5;render()}if(z=="saveProfile"){S.name=q("#name").value;S.username=q("#username").value;render()}if(z=="saveKey"){S.apiKey=q("#key").value.trim();save();alert("Kaydedildi.");render()}if(z=="reset"&&confirm("Yerel ilerleme silinsin mi?")){localStorage.removeItem("linguabot-web");location.reload()}
var l=currentLesson(),ex=l&&l.exercises[S.exerciseIndex];if(!ex)return;if(z=="textAnswer")check(q("#answer").value.trim().toLowerCase()===String(ex.correctAnswer).trim().toLowerCase(),ex);if(z=="sentenceAnswer")check(q("#sentence").textContent.trim()===String(ex.correctAnswer).trim(),ex);if(z=="listen"){if("speechSynthesis"in window){var u=new SpeechSynthesisUtterance(ex.ttsTargetText||ex.correctAnswer);u.lang=S.language;speechSynthesis.speak(u)}}if(z=="speak"&&"webkitSpeechRecognition"in window){var R=new webkitSpeechRecognition();R.lang=S.language;R.onresult=function(ev){var said=ev.results[0][0].transcript;q("#speechResult").textContent="Dedin: "+said;check(said.toLowerCase().replace(/[^a-z\u00C0-\u024F\u3040-\u30ff\uac00-\ud7af\u4e00-\u9fff ]/gi,"").trim()===String(ex.correctAnswer||ex.ttsTargetText).toLowerCase().trim(),ex)};R.start()}});
q("#menu").onclick=function(){q(".sidebar").classList.toggle("open")};q("#language").onclick=function(){q("#langs").showModal()};q("#close").onclick=function(){q("#langs").close()};q("#langGrid").innerHTML=langs.map(function(l){return '<button class="langOpt" data-lang="'+l[0]+'">'+l[1]+" "+l[2]+"</button>"}).join("");document.addEventListener("click",function(e){var b=e.target.closest(".langOpt");if(b){S.language=b.dataset.lang;S.lessonId=null;q("#langs").close();render()}});render();